# Generated by Django 4.2.11 on 2024-05-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_customer_email_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order'},
        ),
    ]
